export const instructions = `Use eda_session first and pin every request to its target UUIDs. Read eda_workflow for your current stage. Measurements default to mm; schematic native units differ from PCB. The client model plans placement and explicit route vertices. No automatic routing is available by default. Inspect geometry and images, modify a small set, read back, then verify. DRC passing is not proof of electrical correctness or a manufacturable design. Typed tools are directly exposed by default; eda_find_tools and eda_tool_schema aid discovery. For existing copper, pads and outline edits, read pcb_get_edit_context and the pcb_editing workflow. Editing availability and complete electrical verification are separate capabilities. Never invent device IDs, pad positions, connected nets, or verification results.`;

export const workflows = {
  start: `1. Read eda_session and choose the exact project/document. 2. Read capabilities and project memory. 3. Record board dimensions, layer stack, functional interfaces, power requirements and unresolved choices. 4. Read the schematic or PCB before editing. Every mutation needs a unique operationId; reuse it only to retrieve the result of the SAME request. Backups are automatic; unknown/partial outcomes require reconciliation, not replay.`,
  schematic: `Choose real library devices with existing symbol/footprint bindings. Inspect pins after placement/rotation; connect by reference and pin number using sch_connect_pins. Organize power flow above a left-to-right signal flow, keep repeated channels consistent, separate functional blocks and use multiple pages when useful. Keep labels away from pins and bodies. Electrical wires must not be used as diagram decorations. Save, export actual netlist, compare intended pin-to-net contracts and run DRC. A boolean DRC response has no error detail. Inspect the full page and detailed regions with eda_screenshot.`,
  placement: `Before routing, inspect board outline, pad positions and connectivity. Resolve mechanical dimensions instead of assuming a board is too large. Fix connector locations/orientations and reserve exit channels. Keep decoupling loops, crystal loops and regulator feedback loops short according to datasheets. Arrange functional regions without breaking necessary returns. Use pcb_review_layout with explicit constraints, then inspect global and local screenshots. Do not encode universal crystal ground or analog/digital ground rules; use the actual circuit and stack-up. Persist the accepted placement intent.`,
  routing: `Read pcb_get_routing_context for the target net and a local screenshot. The model chooses pad endpoints, exact vertices, layer, width and any vias. Use pcb_check_route, correct reported conflicts, then pcb_apply_route with the observed revision. No hidden autorouter or automatic obstacle-crossing fallback is permitted. Route critical short loops first, then power and remaining signals according to the actual constraints. Read back each route and inspect changed regions; run DRC at each completed net. EDA 3.2.149 rounds via diameter/drill to mil increments: 0.6096/0.3048 mm was verified; compare actual dimensions, never assume exact requested sizes. EDA may merge track IDs; validate physical path coverage and do not delete merged copper without reviewing ownership. An obstructed route requires different vertices or placement, not a straight-line fallback.`,
  review: `Read the actual graph of pads/tracks/vias. A network is connected only when all required pads share a conductive component, including valid layer transitions. Check shorts as well as opens. Pours require a separate check for islands, narrow ground necks, splits and return paths; the presence of a GND pour proves none of these. When copper geometry is unsupported, report unknown and do not claim a pass. Compare schematic-to-PCB pin contracts. Save, reopen, read back and inspect fresh global and local screenshots. Final evidence includes BOM, connectivity, DRC, unresolved constraints and backup paths.`,
  recovery: `On a timeout, HTTP 500 or partial write, inspect operation evidence and current geometry before proceeding. An uncertain operation is not retryable merely because the transport disconnected. Use a new operationId only for a reconciled corrective action. Delete only identified primitives belonging to that operation; do not overwrite a document source to undo unrelated edits. Restore a full backup only through an explicitly selected recovery procedure.`,
  pcb_editing: `Read pcb_get_edit_context for exact primitive IDs, native-mil properties and the editing revision; do not substitute the routing revision. Use pcb_update_pad for board pad overrides, pcb_create_copper/pcb_update_copper with kind fill for fixed conductive shapes or pour for refillable boundaries, pcb_update_outline_primitive for selected line/arc/polyline edits, and pcb_replace_outline only for an explicitly selected complete outline set. Preserve locks, unspecified fields, nets and mechanical constraints. Prefer small patches. Numeric polygon source is implicitly closed for copper creation; returned native arrays require explicit unit mil when reused. Official modifications may replace IDs: use the returned verified actual ID. Inspect partial results before corrective writes; do not replay. pcb_rebuild_pours refills copper and is not autorouting; actual poured path units remain uncalibrated, so a successful refill does not prove connectivity. Fixed RF copper is intentional circuitry: preserve radiator/feed geometry and do not impose MCU placement or ground heuristics. Compare requested and actual dimensions, DRC and local images, then save/reopen. Full electrical and RF performance acceptance require independent evidence.`,
} as const;

export const memoryRules = `Project constraints take precedence over heuristics. Observations must contain version, reproduction and evidence; unverified observations are not universal rules. Keep private UUIDs, paths, backups and board files out of public examples.`;
